site_name: Docs
site_description: Enterprise Communication Orchestration Platform Documentation
site_author: Product Documentation Team

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material

  logo: assets/images/full_logo1.png
  favicon: assets/images/full_logo1.png

  palette:
    - scheme: default
      primary: white
      accent: Indigo

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top

  font:
    text: Inter
    code: JetBrains Mono

plugins:
  - search

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Product Guide:
    - Introduction: Product_Guide/overview1.md
    - System Requirements: Product_Guide/system_requirements.md
    - Installation: Product_Guide/installation.md
    - Getting Started: Product_Guide/getting_started.md
  - SMS:
      - Overview: overview.md
      - Architecture: SMS/sms_architecture.md
      - Dashboard: SMS/dashboard/dashboard_index.md
      - Control Centre:
          - Control Centre Overview: SMS/control-centre/index.md
          - DB Configuration: SMS/control-centre/database-setup.md
          - DB Management:
                - Update DB Configuration: SMS/control-centre/update-db-configuration.md
                - View DB Configuration: SMS/control-centre/view-db-configuration.md
          - Service Provider Registration: SMS/control-centre/service-provider-registration.md
          - SP Management:
                - Update Service Provider Details: SMS/control-centre/service-provider-management.md
                - View Service Provider Details: SMS/control-centre/view-sp-details.md
          - Error Control Center: SMS/control-centre/error-retry-management.md
      - Routing Setup:
          - Routing Setup Overview: SMS/routing-setup/index.md
          - Configure Routing Strategy:
                 - Round Robin: SMS/routing-setup/round-robin.md
                 - Percentage Allocation: SMS/routing-setup/percentage-allocation.md
                 - Functional Routing: SMS/routing-setup/functional-routing.md
                 - Header Routing: SMS/routing-setup/header-routing.md
                 - Template Routing: SMS/routing-setup/template-routing.md
                 - Service Type Routing: SMS/routing-setup/service-type-routing.md
                 - Geographic Routing: SMS/routing-setup/geographic-routing.md
          - Create Routing Combinations: SMS/routing-setup/routing-combinations.md
          - Edit Routing Combinations: SMS/routing-setup/edit_routing_combination.md
      - Analytics:
          - Analytics Overview: SMS/analytics/index.md
          - Report & Log: SMS/analytics/report-and-log.md
      - Administration:
          - Administration Overview: SMS/administration/index.md
          - System Audit: SMS/administration/system-audit.md
  - WhatsApp:
      - Overview: whatsapp/index.md
  - FAQ: SMS/reference/faq.md

